#
#
# This will be your plugin config!
#
#
config:
  plugin:
    prefix: "§7[§aSlashWelcome§7]"
    time: 24
    messages:
      - "Welcome to OgreDupe, %player%!"
      - "Do /daily for a key and /kit for some free gear."
