#
#
# This will be your plugin config!
#
#
config:
  plugin:
    prefix: "§7[§aSlashWelcome§7]"
    delay: 24
    messages:
      A:
        - "Welcome to OgreDupe, %player%!"
        - "Do /daily for a key and /kit for some free gear."
      B:
        - "Have fun, %player%!"
        - "Feel free to do /daily for a key and /kit for gear!"
      C:
        - "Good luck, %player%!"
        - "Make sure to pick up your /daily key and your kit!"